[package]
name = "js-runtime"
version = "0.1.0"
edition = "2021"

[features]
default = ["ffi"]
ffi = []
lite = []

#--
[lib]
name = "js_runtime"
crate-type=["rlib", "cdylib"]

[[example]]
name = "runtime"
required-features = ["ffi"]

#--
[dependencies]
slab = "0.4.9"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = [
    "alloc", "ansi", "env-filter", "fmt", "json", "local-time", "matchers",
    "regex", "serde", "smallvec", "thread_local", "time", "tracing",
    "tracing-log", "tracing-serde",
]

[dependencies.tokio]
version = "1.36.0"
features = [
    "rt", "bytes", "fs", "macros", "net", "rt-multi-thread", "signal",
    "socket2", "sync", "time", "tokio-macros", "tracing", "process",
]

[dependencies.futures]
version = "0.3.30"

[dependencies.deno_core]
# TODO: Remove this when deno_core::extension! works without it.
version = "0.262.0"
features = ["include_js_files_for_snapshotting"]

[dependencies.deno_runtime]
version = "0.146.0"
features = ["include_js_files_for_snapshotting"]

[dev-dependencies]
anyhow = "1.0.79"
